name: 'Practice actions'
on:
  push:
    branches:
      - master

  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        run: echo "hello world"
      - name: Run a one-line script
        run: echo testing...
        
